### ISSUE TITLE
Wrong style during hover

### ISSUE THREAD

**Issue by ab7z** [badmacstone/fabulous-table#17]
Hi,

i had some experiences with fabulous-table and it's really great. I recognized that even the `rowAction` is not defined in the table body, the cell changed the cursor by hovering. It caused by this line of css:
 
https://github.com/badmacstone/fabulous-table/blob/d807965aa306d66f8c8ad6c009ea975b1bc8aee9/addon/styles/addon.css#L51

I think it should be looking if `rowAction` is defined and then add the css class to the table cell.

thx

**Comment by dmtask** [comment]
Schauen wir uns nächste Woche mal an.
