### ISSUE TITLE
JS Error in empty Tables

### ISSUE THREAD

**Issue by dmtask** [badmacstone/fabulous-table#20]
We often have empty tables where only the header exists. The data are added dynamically (if they are maintained). But these empty tables bring the following error when scrolling on the page:
`Uncaught TypeError: Cannot read property 'top' of undefined
    at Class.isScrolledToBottom (fabulous-table.js:69)`

So far we always try to create a workaround with us.
@badmacstone I'll try to create a PR for this, then you can take a look and say if you can live with it.

**Comment by fabicious** [comment]
Published in version `1.0.7`
